version: "3.8"

services:
  twp:
    build: .
    env_file:
      - .env
    ports:
      - "${TWP_PORT}:${TWP_PORT}"
    restart: unless-stopped
    depends_on:
      - postgres
      - minio

  # TODO: add golang-migrate script
  postgres:
    image: postgres
    env_file:
      - .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -d ${POSTGRES_DB} -U ${POSTGRES_USER}"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

  # TODO: add minio bucket automatic setup script
  minio:
    image: minio/minio
    env_file:
      - .env
    ports:
      - "${MINIO_API_PORT}:${MINIO_API_PORT}"
      - "${MINIO_CONSOLE_PORT}:${MINIO_CONSOLE_PORT}"
    volumes:
      - minio-data:/data
    command: server /data --console-address ":${MINIO_CONSOLE_PORT}"
    restart: unless-stopped
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl -f http://localhost:${MINIO_CONSOLE_PORT}/minio/health/live || exit 1"
        ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data:
  minio-data:


